### ISSUE TITLE
Prevent player from modifying data from console

### ISSUE THREAD

**Issue by CromulentCoder** [CromulentCoder/Asteroid-Blaster#3]
Currently the high score variable can be accessed and modified via the console. This allows the player to have an absurd amount of score which should not be possible.

**Comment by sgba000p** [comment]
You could put the content of `sketch.js`, where score and highscore are defined, inside of an IIFE

`(function() {
       ....
})();`

By the way, `let` is from ECMAS 6, which is not compatible with IE11. You should use `var`

**Comment by CromulentCoder** [comment]
Yea that should prevent people from accessing it directly. Sadly since the game is run on the client side a little bit of "hacking" will be possible.

**Comment by gezeta-id** [comment]
There are various things you _could_ do about this. Some are easier, but only provide limited "protection". Some will be more robust, but will require more work. I will suggest a couple of them:

The most immediate one would be to simply wrap everything inside an _immediately-invoked function expression_. You know, you get the whole `sketch.js` and wrap it in...

```javascript
(function() {
})();
```

What this achieves is that all [these variables here](https://github.com/CromulentCoder/Asteroid-Blaster/blob/c23f664b932d56f54600a517b5b2cea23a3bc716/public/gamefiles/sketch.js#L20-L22) are not immediately accessible because they are no longer in the global scope.

Of course the protection this offers is quite limited. While one can no longer directly address say `score` in the console, one could instead place a breakpoint on any place inside that, ay in the `draw` function or in the `resetGame` function, then change the value and remove the breakpoint.

You can make it _a bit_ more involved than this. Maybe by using modules or by wrapping the `score` further down into closures. But the result will be similar. Yeah, you'll make it _less easy_ but still not difficult to someone with enough intent and effort.

And there's still an additional problem. All that doesn't matter at all. What actually matters is that the score is correct _when it is sent to the server_. And here the problem still persists. Imagine I set a breakpoint [right about here](https://github.com/CromulentCoder/Asteroid-Blaster/blob/c23f664b932d56f54600a517b5b2cea23a3bc716/public/gamefiles/sketch.js#L279) and just before `updateTable` is called, I manipulate `highscore`.

Or even worse. Imagine I completely bypass the debugger and simply go directly to the _Network_ tab in the dev tools and I let the [POST here](https://github.com/CromulentCoder/Asteroid-Blaster/blob/c23f664b932d56f54600a517b5b2cea23a3bc716/public/gamefiles/sketch.js#L70) to go off normally. But then I just press "Edit and resend". I change the content to whatever score I want, modify the headers accordingly and just send it. I haven't even touched your code at all. I could do the same just by opening the console and just doing my own `fetch`.

The thing is that, ultimately, the only way to actually have some control over what is a "valid score", has to be done somewhere you can trust. And the only place for that is on the server.

How could you do it on the server? There are, again, various ways. And again some require more effort and are more resistant to tampering than others.

As a moderately simple approach, you could take advantage of one characteristic of the game: points can only be gained at a certain rate, which is more or less regular. As per [this line here](https://github.com/CromulentCoder/Asteroid-Blaster/blob/c23f664b932d56f54600a517b5b2cea23a3bc716/public/gamefiles/sketch.js#L235) a new asteroid is produced at least every five seconds (is that it? I'm guessing 60FPS, so 5 seconds), and at most every couple of seconds (a bullet inflicts 1 damage, average mass should be ~100, so you need about 100 hits, one hit per frame, almost two seconds). And, again, the [average mass is about 100](https://github.com/CromulentCoder/Asteroid-Blaster/blob/c23f664b932d56f54600a517b5b2cea23a3bc716/public/gamefiles/sketch.js#L247). So, this means that there is a maximum number of points you can gain in a given time. Let's say something like 50 points per second if you are _really good_ but still don't cheat.

So you could do this: At the start of each game, you make a call to the server just signaling that "a new game was started by this player". You store this somewhere; in particular you store the timestamp of the beginning of the game. Then, when a player sends the score, you do two things before accepting the score as valid. One, you check that you have indeed a _started game_ for that player. Second, you get the current time, calculate the difference with the starting time, say... 198 seconds (3 minutes and a bit). Now you multiply by 50. 9900. Now you can compare with the score submitted. Did they submit an impossible score? Then reject it. If not, accept it. Whether you reject it or not, remember to clean the stored "game started" time for that player.

(A note here: When you reject a score, just don't tell the user. Return a 200 OK but simply discard the score).

Can this be gamed? Sure it can. I can manually send a "game started", wait for 30 minutes and then send a calculated valid but very high score. But then again, does it matter? If someone is willing to spend 30 minutes just waiting to set a score in the leader board, then they probably will do whatever else to cheat. You could make it far harder to cheat, but actually you only need to make it "hard enough that people just won't bother". I think the proposed method is certainly not fool-proof, but it just makes it _boring enough_ that most cheaters won't try.

_If you want_ you could make it a _little_ harder to cheat by sending a "still playing" request, with the current score, every minute or so. This would give you an additional check to validate that the player is indeed playing and is gaining points at a reasonable rate. I don't think you need this, but you could do it.

To make it harder to cheat than this, would probably not only require significant more effort but also could interfere with the game itself. So... personally, I wouldn't bother.

I hope this helps. Or at least gives you some ideas. Sorry for the loooong and boring explanation.

**Comment by CromulentCoder** [comment]
@gezeta-id that was a wonderful explanation with some very insightful ideas. I am aware of all the ways client side script can be manipulated and honestly I was hoping to avoid all that since I made this as a side project to just create something fun. Guess a little bit of protection is required after all.

I'll add the `(function(){....})()` patch for  now until I get time to implement the server side protection. In the meantime if someone wants to take up this issue I'll be very glad.

**Comment by CromulentCoder** [comment]
@sgabaydbg @gezeta-id I have updated the code with some security features. If the previous exploits are eliminated I'd like to close the issue. Let me know if there is still any easy exploit.

**Comment by gezeta-id** [comment]
From a _quick_ glance, the code looks fair. It _should_ work. Probably not make it impossible to cheat, but at least clearly more difficult than before.

The thing is that right now (`Thu, 14 Mar 2019 09:09:32 GMT`) the game seems to not be storing any high scores at all. I mean, I just played a normal game -i.e. no cheating in any way-, got about 900 points, which should be in the leader board, but the score does not get stored. 

It seems that, for some reason, the *socket gets disconnected* and is never reconnected again, and so it just doesn't send the score updates.

_I don't know if this is related or not, but frequently -not always but almost always- when inserting my name and submitting, instead of going into the game, it asks for my name again a second time and then it does go through._

**Comment by CromulentCoder** [comment]
@gezeta-id Yes I noticed that issue as well. The server was wrongly marking non-cheaters as cheaters due to the wrong scoping of my variables. It should be fixed now. 

As for the reason why you might be having to log in twice is probably because of your cached cookies. When you enter the first time, the sever notices cached data and  clears it and doesn't let you enter. But it allows you on the second try.
